#!/usr/bin/env python3
"""Generate p101-inspect's native rule catalog from the JSON policy packs."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
RULE_DIRECTORY = ROOT / "scripts" / "rules"
OUTPUT = ROOT / "programs" / "p101-inspect" / "src" / "rule_catalog.inc"
RULE_KINDS = {
    "forbid-finding",
    "require-finding",
    "forbid-call",
    "require-call",
    "require-edge",
    "require-resource",
}


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def identifier(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", value)


def load_packs() -> list[dict[str, object]]:
    packs: list[dict[str, object]] = []
    for path in sorted(RULE_DIRECTORY.glob("*.json")):
        pack = json.loads(path.read_text(encoding="utf-8"))
        if pack.get("schema") != "p101-rule-pack-v1":
            raise ValueError(f"{path}: unsupported schema")
        name = pack.get("name")
        rules = pack.get("rules")
        if not isinstance(name, str) or not name or not isinstance(rules, list):
            raise ValueError(f"{path}: malformed rule pack")
        seen: set[str] = set()
        for rule in rules:
            if not isinstance(rule, dict) or set(rule) != {
                "id",
                "kind",
                "pattern",
                "title",
                "lesson",
            }:
                raise ValueError(f"{path}: malformed rule")
            if not all(isinstance(rule[key], str) and rule[key] for key in rule):
                raise ValueError(f"{path}: empty rule field")
            if rule["kind"] not in RULE_KINDS:
                raise ValueError(f"{path}: unsupported rule kind {rule['kind']}")
            if rule["id"] in seen:
                raise ValueError(f"{path}: duplicate rule id {rule['id']}")
            seen.add(rule["id"])
        packs.append(pack)
    return packs


def render(packs: list[dict[str, object]]) -> str:
    lines = [
        "/* Generated by scripts/generators/generate-inspect-rule-catalog.py. */",
        "",
    ]
    for pack in packs:
        name = str(pack["name"])
        symbol = identifier(name)
        lines.append(f"static const struct rule_definition rule_pack_{symbol}[] =")
        lines.append("{")
        for rule in pack["rules"]:  # type: ignore[index]
            assert isinstance(rule, dict)
            values = [c_string(str(rule[key])) for key in ("id", "kind", "pattern", "title", "lesson")]
            lines.append("    {" + ", ".join(values) + "},")
        lines.extend(("};", ""))
    lines.append("static const struct rule_pack_definition rule_packs[] =")
    lines.append("{")
    for pack in packs:
        name = str(pack["name"])
        symbol = identifier(name)
        lines.append(
            f"    {{{c_string(name)}, rule_pack_{symbol}, "
            f"sizeof(rule_pack_{symbol}) / sizeof(rule_pack_{symbol}[0])}},"
        )
    lines.extend(("};", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render(load_packs())
    if args.check:
        return 0 if OUTPUT.is_file() and OUTPUT.read_text(encoding="utf-8") == generated else 1
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
