#!/usr/bin/env python3
"""Materialize p101-tool-playground track docs from the wrapper graph.

The authoritative grouping lives in scripts/docs/lib-function-graph.json. This
script turns that graph into student/instructor-facing track directories inside
this playground repository.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any


# The generator is scripts-owned; its outputs live in the sibling playgrounds
# repository.
ROOT = Path(__file__).resolve().parents[2]
PLAYGROUND = ROOT / "playgrounds"
GRAPH = ROOT / "scripts" / "docs" / "lib-function-graph.json"
TRACKS = PLAYGROUND / "tracks"

P101_LIBRARIES = [
    "p101_error",
    "p101_env",
    "p101_tool_event",
    "p101_c",
    "p101_io",
    "p101_filesystem",
    "p101_memory",
    "p101_process",
    "p101_thread",
    "p101_sync",
    "p101_ipc",
    "p101_network",
    "p101_terminal",
    "p101_time",
    "p101_identity",
    "p101_text",
    "p101_locale",
    "p101_math",
    "p101_search",
    "p101_dynamic_linking",
    "p101_diagnostics",
    "p101_database",
    "p101_cli",
    "p101_random",
    "p101_host",
    "p101_fsm",
    "p101_util",
    "p101_convert",
    "p101_c_facts",
    "m",
]

SHARED_LINKS = {
    "CMakeLists.txt": "../../CMakeLists.txt",
    "cmake": "../../cmake",
    ".flags": "../../../.flags",
    "sanitizers.txt": "../../../scripts/sanitizers.txt",
    "supported_c_compilers.txt": "../../../scripts/supported_c_compilers.txt",
}

REFERENCE_EXAMPLES = {
    "p101-orientation": (
        "lib_env_examples",
        "env/get_tracer/main.c",
    ),
    "c-memory-runtime": (
        "lib_c_examples",
        "stdlib/abs/main.c",
    ),
    "c-memory-bytes": (
        "lib_endian_examples",
        "round_trip/main.c",
    ),
    "c-char-classification": (
        "lib_c_examples",
        "ctype/isalpha/main.c",
    ),
    "c-stdio-character-buffering": (
        "lib_c_examples",
        "stdio/puts/main.c",
    ),
    "error-handling": (
        "lib_error_examples",
        "lifecycle/main.c",
    ),
    "environment-lifecycle": (
        "lib_env_examples",
        "env/get_tracer/main.c",
    ),
    "fsm": (
        "lib_fsm_examples",
        "fsm_run/main.c",
    ),
}


def reference_example(track_name: str) -> dict[str, str] | None:
    reference = REFERENCE_EXAMPLES.get(track_name)
    if reference is None:
        return None
    repository, path = reference
    return {
        "repository": repository,
        "path": path,
        "workspace_path": f"examples/{repository}/{path}",
        "url": f"https://github.com/programming101dev/{repository}/blob/main/{path}",
    }


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def load_graph() -> dict[str, Any]:
    return json.loads(GRAPH.read_text(encoding="utf-8"))


def domain_functions(graph: dict[str, Any], domain: str) -> list[str]:
    return list(graph["domains"][domain]["functions"])


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def format_c(path: Path) -> None:
    formatter_name = os.environ.get("CLANG_FORMAT", "clang-format")
    formatter = shutil.which(formatter_name)
    if formatter is None:
        raise RuntimeError(f"could not find C formatter: {formatter_name}")
    subprocess.run([formatter, "-i", str(path)], check=True)


def ensure_symlink(path: Path, target: str) -> None:
    if path.is_symlink():
        if os.readlink(path) == target:
            return
        path.unlink()
    elif path.exists():
        return
    path.symlink_to(target)


def markdown_list(items: list[str]) -> str:
    if not items:
        return "- _None._"
    return "\n".join(f"- `{item}`" for item in items)


def c_string(text: str) -> str:
    return json.dumps(text)


def cmake_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def track_readme(graph: dict[str, Any], track: dict[str, Any], index: int) -> str:
    domains = track["domains"]
    reference = reference_example(track["track"])
    lines = [
        f"# {track['track']}",
        "",
        "<!-- generated by scripts/generators/sync-playground-track-map.py; edit the graph/classifier, then regenerate -->",
        "",
        f"Track number: `{index:02d}`",
        "",
        f"Wrapper count: `{track['function_count']}`",
        "",
        "This directory is a defect-and-repair curriculum map. Its small executable",
        "is only a neutral inventory/linkage harness; it is not the canonical correct",
        "example for this wrapper family.",
        "",
        "```sh",
        f"cd tracks/{index:02d}-{slug(track['track'])}",
        f"../../track-runner.sh {slug(track['track'])}",
        "```",
        "",
        "Curated lesson guide: [TRACK.md](./TRACK.md).",
        "",
        "## Purpose",
        "",
        track["purpose"],
        "",
        "## Domains",
        "",
    ]
    lines.extend(f"- `{domain}` ({graph['domains'][domain]['count']} wrappers)" for domain in domains)
    lines.extend(
        [
            "",
            "## Defect-and-repair lesson arc",
            "",
            "1. When present, read the intentional defect and its `expected.json` oracle.",
            "2. Run that case with the p101-test corpus engine and read its diagnostic ID.",
            "3. Use the linked correct example only as a reference for normal API use.",
            "4. Repair the defect without copying unrelated example code.",
            "5. Re-run the same oracle and keep the repaired behavior as evidence.",
            "",
        ]
    )
    if reference is not None:
        lines.extend(
            [
                "## Correct-use reference",
                "",
                f"- Workspace: `../../../{reference['workspace_path']}`",
                f"- GitHub: [{reference['repository']}/{reference['path']}]({reference['url']})",
                "",
                "The example repository owns the good path. This playground owns the",
                "mistake, its diagnostic, and the repair exercise.",
                "",
            ]
        )
    lines.extend(["## Wrapper inventory", ""])
    for domain in domains:
        funcs = domain_functions(graph, domain)
        lines.extend([f"### `{domain}`", "", markdown_list(funcs), ""])
    return "\n".join(lines)


def track_lesson(track: dict[str, Any], index: int) -> str:
    reference = reference_example(track["track"])
    reference_section = (
        [
            "## Correct-use reference",
            "",
            f"The good path lives in `../../../{reference['workspace_path']}`.",
            f"On GitHub: [{reference['repository']}/{reference['path']}]({reference['url']}).",
            "Use it to understand ordinary API shape. Do not copy its answer over the",
            "defect; explain and repair the violated invariant instead.",
            "",
        ]
        if reference is not None
        else [
            "## Correct-use reference",
            "",
            "No canonical example is linked for this family yet. Add correct-use code",
            "to the owning `examples/<repo>` repository, then add only its reference",
            "here. Do not put the good-path implementation in the playground.",
            "",
        ]
    )
    return "\n".join(
        [
            f"# Track {index:02d}: {track['track']}",
            "",
            "<!-- generated by scripts/generators/sync-playground-track-map.py; edit the graph/classifier, then regenerate -->",
            "",
            "## Goal",
            "",
            track["purpose"],
            "",
            "## Student workflow",
            "",
            "```sh",
            f"../../track-runner.sh {slug(track['track'])}",
            "# inspect src/main.c and include/track_info.h",
            "cmake -S . -B build -DP101_BUILD_LEVEL=2",
            "cmake --build build",
            "```",
            "",
            "A complete lesson begins with an intentional corpus defect, not with this",
            "neutral inventory harness. When the lesson catalog names a case, run it,",
            "read its diagnostic, repair the invariant, and replay the same oracle.",
            "Without that case, this track remains a curriculum map rather than a",
            "finished exercise.",
            "",
            "## Local files",
            "",
            "- `src/main.c` — neutral inventory/linkage harness, not a good-path example.",
            "- `include/track_info.h` — generated track metadata.",
            "- `config.cmake` — local target and link configuration.",
            "- `test/CMakeLists.txt` — local smoke test for this track binary.",
            "- `../../track-runner.sh` — the single runner shared by every track.",
            "",
            "## Habit to practice",
            "",
            "Keep functions file-local with `static` unless they are part of the",
            "track's real API, pass `env`/`err` through code that can fail, use p101",
            "wrappers instead of direct libc/POSIX calls, and make cleanup visible.",
            "",
            *reference_section,
            "## Repair progression",
            "",
            "1. Run the lesson catalog's intentional defect with `programs/p101-test/test-corpus`.",
            "2. Read its stable finding ID and linked playground lesson.",
            "3. State the invariant the defect violates.",
            "4. Repair the code and replay the same case.",
            "5. Keep the oracle so the mistake cannot silently return.",
            "",
        ]
    )


def track_json(graph: dict[str, Any], track: dict[str, Any], index: int) -> str:
    data = {
        "track": track["track"],
        "title": track["track"].replace("-", " "),
        "order": index,
        "generated": True,
        "wrapper_count": track["function_count"],
        "purpose": track["purpose"],
        "reference_example": reference_example(track["track"]),
        "coverage_claim": "inventory-and-linkage",
        "domains": [
            {
                "name": domain,
                "function_count": graph["domains"][domain]["count"],
                "functions": domain_functions(graph, domain),
            }
            for domain in track["domains"]
        ],
        "local_project": {
            "source": "src/main.c",
            "header": "include/track_info.h",
            "binary": f"p101-track-{slug(track['track'])}",
        },
    }
    return json.dumps(data, indent=2) + "\n"


def track_header(track: dict[str, Any], index: int) -> str:
    guard = f"P101_TRACK_{index:02d}_{slug(track['track']).upper().replace('-', '_')}_INFO_H"
    return "\n".join(
        [
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            f"#define P101_TRACK_SLUG {c_string(track['track'])}",
            f"#define P101_TRACK_TITLE {c_string(track['track'].replace('-', ' '))}",
            f"#define P101_TRACK_PURPOSE {c_string(track['purpose'])}",
            "",
            "enum",
            "{",
            f"    P101_TRACK_INDEX         = {index},",
            f"    P101_TRACK_WRAPPER_COUNT = {track['function_count']}",
            "};",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )


def track_main(graph: dict[str, Any], track: dict[str, Any], index: int) -> str:
    functions: list[str] = []
    for domain in track["domains"]:
        functions.extend(domain_functions(graph, domain))
    if not functions:
        functions = ["none"]
    function_lines = ",\n".join(f"    {c_string(function)}" for function in functions)
    extra_includes: list[str] = []
    demo_function: list[str] = []
    demo_call: list[str] = []
    return "\n".join(
        [
            '#include "track_info.h"',
            "#include <p101_c/p101_stdio.h>",
            "#include <p101_c/p101_stdlib.h>",
            "#include <p101_env/env.h>",
            "#include <p101_error/error.h>",
            *extra_includes,
            "#include <stddef.h>",
            "#include <stdlib.h>",
            "",
            "static const char *const wrapper_functions[] = {",
            function_lines,
            "};",
            "",
            "static const size_t wrapper_function_count = sizeof(wrapper_functions) / sizeof(wrapper_functions[0]);",
            "",
            "static int write_line(const struct p101_env *env, struct p101_error *err, const char *line)",
            "{",
            "    int ret_val;",
            "",
            "    ret_val = p101_fprintf(env, err, stdout, \"%s\\n\", line);",
            "    if(ret_val < 0 || p101_error_has_error(err))",
            "    {",
            "        return EXIT_FAILURE;",
            "    }",
            "",
            "    return EXIT_SUCCESS;",
            "}",
            "",
            "static int write_wrapper_inventory(const struct p101_env *env, struct p101_error *err)",
            "{",
            "    int ret_val;",
            "",
            "    ret_val = EXIT_SUCCESS;",
            "    for(size_t i = 0; i < wrapper_function_count; i++)",
            "    {",
            "        if(p101_fprintf(env, err, stdout, \"- %s\\n\", wrapper_functions[i]) < 0 || p101_error_has_error(err))",
            "        {",
            "            ret_val = EXIT_FAILURE;",
            "            break;",
            "        }",
            "    }",
            "",
            "    return ret_val;",
            "}",
            *demo_function,
            "",
            "int main(void)",
            "{",
            "    struct p101_error *err;",
            "    struct p101_env   *env;",
            "    int                ret_val;",
            "",
            "    ret_val = EXIT_FAILURE;",
            "    err     = p101_error_create(false);",
            "    if(err == NULL)",
            "    {",
            "        return EXIT_FAILURE;",
            "    }",
            "",
            "    env = p101_env_create(err, NULL);",
            "    if(env == NULL || p101_error_has_error(err))",
            "    {",
            "        goto done;",
            "    }",
            "",
            "    if(p101_fprintf(env, err, stdout, \"Track %d: %s\\n\", P101_TRACK_INDEX, P101_TRACK_TITLE) < 0 || p101_error_has_error(err))",
            "    {",
            "        goto done;",
            "    }",
            "    if(write_line(env, err, P101_TRACK_PURPOSE) != EXIT_SUCCESS)",
            "    {",
            "        goto done;",
            "    }",
            "    if(p101_fprintf(env, err, stdout, \"Wrapper count: %d\\n\", P101_TRACK_WRAPPER_COUNT) < 0 || p101_error_has_error(err))",
            "    {",
            "        goto done;",
            "    }",
            "    if(write_line(env, err, \"Wrappers in this track:\") != EXIT_SUCCESS)",
            "    {",
            "        goto done;",
            "    }",
            "    if(write_wrapper_inventory(env, err) != EXIT_SUCCESS)",
            "    {",
            "        goto done;",
            "    }",
            "",
            *demo_call,
            "    ret_val = EXIT_SUCCESS;",
            "",
            "done:",
            "    p101_env_destroy(env);",
            "    p101_error_destroy(err);",
            "    return ret_val;",
            "}",
            "",
        ]
    )


def track_config(track: dict[str, Any], index: int) -> str:
    slug_text = slug(track["track"])
    link_libraries = "\n        ".join(P101_LIBRARIES)
    return "\n".join(
        [
            f'set(PROJECT_NAME "p101-track-{cmake_string(slug_text)}")',
            'set(PROJECT_VERSION "1.0.0")',
            f'set(PROJECT_DESCRIPTION "Standalone p101 playground track: {cmake_string(track["track"])}")',
            'set(PROJECT_LANGUAGE "C")',
            "",
            "set(CMAKE_C_STANDARD 17)",
            "set(CMAKE_C_STANDARD_REQUIRED ON)",
            "set(CMAKE_C_EXTENSIONS OFF)",
            "",
            "set(STANDARD_FLAGS",
            "        -D_POSIX_C_SOURCE=200809L",
            "        -D_XOPEN_SOURCE=700",
            "        -Werror",
            ")",
            "",
            "set(DARWIN_STANDARD_FLAGS",
            "        -D_DARWIN_C_SOURCE",
            ")",
            "",
            "set(LINUX_STANDARD_FLAGS)",
            "set(BSD_STANDARD_FLAGS)",
            "",
            "get_filename_component(P101_WORKSPACE_ROOT \"${CMAKE_CURRENT_SOURCE_DIR}/../../..\" ABSOLUTE)",
            "file(GLOB _P101_TRACK_LIBRARY_REPOS LIST_DIRECTORIES true \"${P101_WORKSPACE_ROOT}/libraries/lib_*\")",
            "list(SORT _P101_TRACK_LIBRARY_REPOS)",
            "set(_P101_TRACK_INCLUDE_DIRS \"\")",
            "set(_P101_TRACK_LINK_DIRS \"\")",
            "foreach (_p101_library_repo IN LISTS _P101_TRACK_LIBRARY_REPOS)",
            "    get_filename_component(_p101_library_name \"${_p101_library_repo}\" NAME)",
            "    if (_p101_library_name MATCHES \"^lib_(posix|posix_optional|posix_xsi|unix)$\")",
            "        continue()",
            "    endif ()",
            "    if (IS_DIRECTORY \"${_p101_library_repo}/include\")",
            "        list(APPEND _P101_TRACK_INCLUDE_DIRS \"${_p101_library_repo}/include\")",
            "    endif ()",
            "    if (EXISTS \"${_p101_library_repo}/.last-build-dir\")",
            "        file(READ \"${_p101_library_repo}/.last-build-dir\" _p101_last_build_dir)",
            "        string(STRIP \"${_p101_last_build_dir}\" _p101_last_build_dir)",
            "        if (IS_DIRECTORY \"${_p101_library_repo}/${_p101_last_build_dir}\")",
            "            list(APPEND _P101_TRACK_LINK_DIRS \"${_p101_library_repo}/${_p101_last_build_dir}\")",
            "        endif ()",
            "    endif ()",
            "    file(GLOB _p101_library_build_dirs LIST_DIRECTORIES true \"${_p101_library_repo}/build*\")",
            "    list(SORT _p101_library_build_dirs)",
            "    foreach (_p101_library_build_dir IN LISTS _p101_library_build_dirs)",
            "        if (IS_DIRECTORY \"${_p101_library_build_dir}\")",
            "            list(APPEND _P101_TRACK_LINK_DIRS \"${_p101_library_build_dir}\")",
            "        endif ()",
            "    endforeach ()",
            "endforeach ()",
            "list(REMOVE_DUPLICATES _P101_TRACK_INCLUDE_DIRS)",
            "list(REMOVE_DUPLICATES _P101_TRACK_LINK_DIRS)",
            "set(P101_PUBLIC_INCLUDE_DIRS \"${_P101_TRACK_INCLUDE_DIRS}\" CACHE STRING \"Track p101 include dirs\" FORCE)",
            "set(P101_PUBLIC_LINK_DIRS \"${_P101_TRACK_LINK_DIRS}\" CACHE STRING \"Track p101 link dirs\" FORCE)",
            "",
            "set(EXECUTABLE_TARGETS main)",
            "set(LIBRARY_TARGETS \"\")",
            f"set(main_OUTPUT_NAME p101-track-{slug_text})",
            "",
            "set(main_SOURCES",
            "        src/main.c",
            ")",
            "",
            "set(main_HEADERS",
            "        include/track_info.h",
            ")",
            "",
            "set(main_LINK_LIBRARIES",
            f"        {link_libraries}",
            ")",
            "",
        ]
    )


def track_test_cmake(track: dict[str, Any]) -> str:
    binary_name = f"p101-track-{slug(track['track'])}"
    return "\n".join(
        [
            "cmake_minimum_required(VERSION 3.14)",
            f"project({binary_name}-tests C)",
            "enable_testing()",
            "",
            "if (NOT DEFINED P101_SOURCE_BUILD_DIR)",
            "    message(FATAL_ERROR \"P101_SOURCE_BUILD_DIR is required; configure the track with P101_BUILD_LEVEL=2\")",
            "endif ()",
            f"set(_P101_TRACK_BINARY \"${{P101_SOURCE_BUILD_DIR}}/{binary_name}\")",
            "if (NOT EXISTS \"${_P101_TRACK_BINARY}\")",
            "    message(FATAL_ERROR \"Track binary not found: ${_P101_TRACK_BINARY}. Build the track first.\")",
            "endif ()",
            "",
            "add_test(NAME track-runs COMMAND \"${_P101_TRACK_BINARY}\")",
            "",
        ]
    )


def materialize_track_project(graph: dict[str, Any], track: dict[str, Any], index: int) -> None:
    track_dir = TRACKS / f"{index:02d}-{slug(track['track'])}"
    track_dir.mkdir(parents=True, exist_ok=True)

    for name, target in SHARED_LINKS.items():
        ensure_symlink(track_dir / name, target)

    for retired_name in ("build.sh", "change-compiler.sh", "test.sh", "run.sh"):
        retired_path = track_dir / retired_name
        if retired_path.is_symlink() or retired_path.is_file():
            retired_path.unlink()

    # A track may be copied out of this repository for a class exercise. Keep
    # repository policy files materialized rather than symlinked so the copy
    # retains its license and ignore policy without the workspace.
    write(track_dir / ".gitignore", (PLAYGROUND / ".gitignore").read_text(encoding="utf-8"))
    write(track_dir / "LICENSE", (PLAYGROUND / "LICENSE").read_text(encoding="utf-8"))
    write(track_dir / "README.md", track_readme(graph, track, index))
    write(track_dir / "TRACK.md", track_lesson(track, index))
    write(track_dir / "track.json", track_json(graph, track, index))
    write(track_dir / "include" / "track_info.h", track_header(track, index))
    main_source = track_dir / "src" / "main.c"
    write(main_source, track_main(graph, track, index))
    format_c(main_source)
    write(track_dir / "config.cmake", track_config(track, index))
    write(track_dir / "test" / "CMakeLists.txt", track_test_cmake(track))


def tracks_index(graph: dict[str, Any], tracks: list[dict[str, Any]]) -> str:
    repo = graph["repository_recommendation"]
    lines = [
        "# Playground tracks",
        "",
        "<!-- generated by scripts/generators/sync-playground-track-map.py; edit the graph/classifier, then regenerate -->",
        "",
        "The playground is one repository with many small tracks. The goal is to",
        "organize intentional defects and repair lessons while assigning every p101",
        "wrapper exactly one curriculum home. Correct programs live in examples/.",
        "",
        "## Coverage",
        "",
        f"- Wrappers assigned to a track: `{repo['covered_function_count']}`",
        f"- Unassigned wrappers/domains: `{repo['uncovered_function_count']}`",
        f"- Tracks linked to canonical correct examples: `{len(REFERENCE_EXAMPLES)}`",
        f"- Track count: `{repo['track_count']}`",
        "- Orientation pre-track: `00-p101-orientation`",
        "- Misc tracks/domains are intentionally forbidden.",
        "",
        "## Track list",
        "",
        "| # | Track | Wrappers | Reference | Purpose |",
        "| ---: | --- | ---: | --- | --- |",
        "| 00 | [`p101-orientation`](00-p101-orientation/README.md) | 0 | `lib_env_examples` | Defect-reading orientation for env, err, wrappers, and tools. |",
    ]
    for index, track in enumerate(tracks, start=1):
        path = f"{index:02d}-{slug(track['track'])}/README.md"
        reference = reference_example(track["track"])
        evidence = f"`{reference['repository']}`" if reference is not None else "pending"
        lines.append(f"| {index:02d} | [`{track['track']}`]({path}) | {track['function_count']} | {evidence} | {track['purpose']} |")
    lines.extend(
        [
            "",
            "## How to use this",
            "",
            "Each track owns a defect family, diagnostic route, and repair sequence.",
            "The local executable is only an inventory/linkage harness. It is never",
            "the canonical good path and is never counted as behavior coverage.",
            "Correct examples live in the owning examples/<repo> repository and are",
            "linked rather than copied into the playground.",
            "",
            "Regenerate after changing wrapper libraries or graph classification:",
            "",
            "```sh",
            "../../scripts/generators/analyze-lib-function-graph.py",
            "../../scripts/generators/sync-playground-track-map.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def manifest(graph: dict[str, Any], tracks: list[dict[str, Any]]) -> str:
    data = {
        "source": str(GRAPH.relative_to(ROOT)),
        "repository": graph["repository_recommendation"]["repository"],
        "orientation_track": {
            "index": 0,
            "track": "p101-orientation",
            "directory": "00-p101-orientation",
            "function_count": 0,
            "purpose": "Generated negative-control pre-track for env, err, wrappers, and tools.",
            "reference_example": reference_example("p101-orientation"),
            "coverage_claim": "negative-control-and-linkage",
        },
        "track_count": len(tracks),
        "covered_function_count": graph["repository_recommendation"]["covered_function_count"],
        "uncovered_function_count": graph["repository_recommendation"]["uncovered_function_count"],
        "coverage_definition": "Each wrapper is assigned to one primary track; assignment alone is not behavior coverage.",
        "reference_example_track_count": len(REFERENCE_EXAMPLES),
        "tracks": [
            {
                "index": index,
                "track": track["track"],
                "directory": f"{index:02d}-{slug(track['track'])}",
                "function_count": track["function_count"],
                "purpose": track["purpose"],
                "reference_example": reference_example(track["track"]),
                "coverage_claim": "inventory-and-linkage",
                "domains": [
                    {
                        "name": domain,
                        "function_count": graph["domains"][domain]["count"],
                        "functions": domain_functions(graph, domain),
                    }
                    for domain in track["domains"]
                ],
            }
            for index, track in enumerate(tracks, start=1)
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def main() -> int:
    graph = load_graph()
    repo = graph["repository_recommendation"]
    tracks = repo["tracks"]
    if repo["uncovered_function_count"] != 0:
        raise RuntimeError("track map has uncovered wrappers/domains")
    if any("misc" in domain for domain in graph["domains"]):
        raise RuntimeError("misc domains are not allowed")

    TRACKS.mkdir(parents=True, exist_ok=True)
    write(TRACKS / "README.md", tracks_index(graph, tracks))
    write(TRACKS / "manifest.json", manifest(graph, tracks))

    orientation = {
        "track": "p101-orientation",
        "function_count": 0,
        "purpose": "Learn env/error setup, the p101 wrapper boundary, and how the playground tools report what they observe.",
        "domains": [],
    }
    materialize_track_project(graph, orientation, 0)

    for index, track in enumerate(tracks, start=1):
        materialize_track_project(graph, track, index)

    print(f"wrote {TRACKS / 'README.md'}")
    print(f"wrote {TRACKS / 'manifest.json'}")
    print(f"wrote {len(tracks) + 1} standalone track projects under {TRACKS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
