name: p101 stack

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: brew install cmake cppcheck llvm gcovr
      - name: Check after update-all
        run: ./check-after-update-all.sh -c clang -x clang++

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y cmake clang clang-tidy clang-format cppcheck gcovr
      - name: Check after update-all
        run: ./check-after-update-all.sh -c clang -x clang++

  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check in FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          prepare: |
            pkg install -y bash cmake llvm cppcheck py311-gcovr
          run: |
            bash ./check-after-update-all.sh -c clang -x clang++
